-- MySQL Script generated by MySQL Workbench
-- Fri Dec  9 13:45:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MayoLama
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MayoLama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MayoLama` DEFAULT CHARACTER SET utf8 ;
USE `MayoLama` ;

-- -----------------------------------------------------
-- Table `MayoLama`.`Lama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MayoLama`.`Lama` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `gender` ENUM('W', 'M') NOT NULL,
  `biotext` BLOB NOT NULL,
  `profilepicture` BLOB NOT NULL,
  `pictures` BLOB NULL,
  `subscriptions` BLOB NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayoLama`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MayoLama`.`User` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NULL,
  `biotext` BLOB NULL,
  `profileimage` BLOB NULL,
  `isAdmin` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayoLama`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MayoLama`.`Seller` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NULL,
  `biotext` BLOB NULL,
  `profileimage` BLOB NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayoLama`.`Subscriptions_Users_Sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MayoLama`.`Subscriptions_Users_Sellers` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Subscription` INT UNSIGNED NOT NULL,
  `ID_User_Seller` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayoLama`.`Subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MayoLama`.`Subscriptions` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `benefits` BLOB NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayoLama`.`Subscriptions_Lamas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MayoLama`.`Subscriptions_Lamas` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Subscription` INT UNSIGNED NOT NULL,
  `ID_Lama` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE USER 'MayoLamaBeheer' IDENTIFIED BY 'mayolama';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
